name: Auto Deploy

on:
  push:
      branches: [main]

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Install Yarn
          run: npm install -g yarn
        - name: Build
          run: |
            yarn && BUILDING=true yarn generate
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            deploy_key: ${{ secrets.ACTION_DEPLOY_KEY }}
            publish_dir: ./out

